### ISSUE TITLE
I cannot find train/val36_imgid2img.pkl file in /utils.

### ISSUE THREAD

**Issue by exquisitedice** [yanxinzju/CSS-VQA#2]
https://github.com/yanxinzju/CSS-VQA/blob/9c422f3e34e8bab2ee26af99ec4a0949f81d8548/dataset.py#L189

maybe you can give me a link, so I can download this file(BaiduYun will be ok).

thanks!

**Comment by yanxinzju** [comment]
hello, we don't use the hdf5, so this file is not needed
