### ISSUE TITLE
Upload files to a different server

### ISSUE THREAD

**Issue by imri** [yanxinzju/CSS-VQA#3]
Hi, 

I find your work exciting! can you please upload the features and utils folders to a different server? 
The current server is not accessible outside of China.

**Comment by yanxinzju** [comment]
Hello,
We will upload the data to Google Cloud Disk in the next few days.

**Comment by yanxinzju** [comment]
Hello,
You can download the data from https://drive.google.com/drive/folders/13e-b76otJukupbjfC-n1s05L202PaFKQ?usp=sharing
