### ISSUE TITLE
Hintscore and type, no_type masks

### ISSUE THREAD

**Issue by gri1** [yanxinzju/CSS-VQA#6]
Hello!
Could you explain how did you generate the files corresponding to hintscores (e.g., `test_cpv2_hintscore.json`) and the type and no_type masks (e.g., `cpv2_type_mask.json` and `cpv2_notype_mask.json`)?

**Comment by yanxinzju** [comment]
hello，we follow the method proposed by "Self-Critical Reasoning for Robust Visual Question Answering", you can get the code by https://github.com/jialinwu17/self_critical_vqa

**Comment by bxwldljh** [comment]
hi, i find that "Self-Critical Reasoning for Robust Visual Question Answering" does not provide the code as you said, can you provide the code corresponding to cpv2_type_mask. json and cpv2_notype_mask. json?

**Comment by JuneHou** [comment]
> hi, i find that "Self-Critical Reasoning for Robust Visual Question Answering" does not provide the code as you said, can you provide the code corresponding to cpv2_type_mask. json and cpv2_notype_mask. json?

Have you find how to get these two files?
